class Perfil {
      final List<String>img1=[
      "assets/images/perfil/cebra-amarillo.png",
      "assets/images/perfil/cebra-celeste.png",
      "assets/images/perfil/cebra-morado.png",
      "assets/images/perfil/cebra-naranja.png",
      "assets/images/perfil/cebra-rojo.png",
      "assets/images/perfil/cebra-rosa.png",
      "assets/images/perfil/cebra-verde.png",
      "assets/images/perfil/cerdo-amarillo.png",
      "assets/images/perfil/cerdo-celeste.png",
      "assets/images/perfil/cerdo-morado.png",
      "assets/images/perfil/cerdo-naranja.png",
      "assets/images/perfil/cerdo-rojo.png",
      "assets/images/perfil/cerdo-rosa.png",
      "assets/images/perfil/cerdo-verde.png"
      ];

      final List<String>img2=[
            "assets/images/perfil/delfin-amarillo.png",
            "assets/images/perfil/delfin-celeste.png",
            "assets/images/perfil/delfin-morado.png",
            "assets/images/perfil/delfin-naranja.png",
            "assets/images/perfil/delfin-rojo.png",
            "assets/images/perfil/delfin-rosa.png",
            "assets/images/perfil/delfin-verde.png",
            "assets/images/perfil/elefante-amarillo.png",
            "assets/images/perfil/elefante-celeste.png",
            "assets/images/perfil/elefante-morado.png",
            "assets/images/perfil/elefante-naranja.png",
            "assets/images/perfil/elefante-rojo.png",
            "assets/images/perfil/elefante-rosa.png",
            "assets/images/perfil/elefante-verde.png"
      ];

      final List<String>img3=[
            "assets/images/perfil/mapache-amarillo.png",
            "assets/images/perfil/mapache-celeste.png",
            "assets/images/perfil/mapache-morado.png",
            "assets/images/perfil/mapache-naranja.png",
            "assets/images/perfil/mapache-rojo.png",
            "assets/images/perfil/mapache-rosa.png",
            "assets/images/perfil/mapache-verde.png",
            "assets/images/perfil/panda-amarillo.png",
            "assets/images/perfil/panda-celeste.png",
            "assets/images/perfil/panda-morado.png",
            "assets/images/perfil/panda-naranja.png",
            "assets/images/perfil/panda-rojo.png",
            "assets/images/perfil/panda-rosa.png",
            "assets/images/perfil/panda-verde.png"
      ];

      final List<String>img4=[
            "assets/images/perfil/cebra-amarillo.png",
            "assets/images/perfil/cebra-celeste.png",
            "assets/images/perfil/cebra-morado.png",
            "assets/images/perfil/cebra-naranja.png",
            "assets/images/perfil/cebra-rojo.png",
            "assets/images/perfil/cebra-rosa.png",
            "assets/images/perfil/cebra-verde.png",
            "assets/images/perfil/cerdo-amarillo.png",
            "assets/images/perfil/cerdo-celeste.png",
            "assets/images/perfil/cerdo-morado.png",
            "assets/images/perfil/cerdo-naranja.png",
            "assets/images/perfil/cerdo-rojo.png",
            "assets/images/perfil/cerdo-rosa.png",
            "assets/images/perfil/cerdo-verde.png",
            "assets/images/perfil/delfin-amarillo.png",
            "assets/images/perfil/delfin-celeste.png",
            "assets/images/perfil/delfin-morado.png",
            "assets/images/perfil/delfin-naranja.png",
            "assets/images/perfil/delfin-rojo.png",
            "assets/images/perfil/delfin-rosa.png",
            "assets/images/perfil/delfin-verde.png",
            "assets/images/perfil/elefante-amarillo.png",
            "assets/images/perfil/elefante-celeste.png",
            "assets/images/perfil/elefante-morado.png",
            "assets/images/perfil/elefante-naranja.png",
            "assets/images/perfil/elefante-rojo.png",
            "assets/images/perfil/elefante-rosa.png",
            "assets/images/perfil/elefante-verde.png",
            "assets/images/perfil/mapache-amarillo.png",
            "assets/images/perfil/mapache-celeste.png",
            "assets/images/perfil/mapache-morado.png",
            "assets/images/perfil/mapache-naranja.png",
            "assets/images/perfil/mapache-rojo.png",
            "assets/images/perfil/mapache-rosa.png",
            "assets/images/perfil/mapache-verde.png",
            "assets/images/perfil/panda-amarillo.png",
            "assets/images/perfil/panda-celeste.png",
            "assets/images/perfil/panda-morado.png",
            "assets/images/perfil/panda-naranja.png",
            "assets/images/perfil/panda-rojo.png",
            "assets/images/perfil/panda-rosa.png",
            "assets/images/perfil/panda-verde.png"
      ];

      final List<String>users=[
            "CebraAmarilla",
            "CebraCeleste",
            "CebraMorada",
            "CebraNaranja",
            "CebraRoja",
            "CebraRosa",
            "CebraVerde",
            "CerditoAmarillo",
            "CerditoCeleste",
            "CerditoMorado",
            "CerditoNaranja",
            "CerditoRojo",
            "CerditoRosa",
            "CerditoVerde",
            "DelfinAmarillo",
            "DelfinCeleste",
            "DelfinMorado",
            "DelfinNaranja",
            "DelfinRojo",
            "DelfinRosa",
            "DelfinVerde",
            "ElefanteAmarillo",
            "ElefanteCeleste",
            "ElefanteMorado",
            "ElefanteNaranja",
            "ElefanteRojo",
            "ElefanteRosa",
            "ElefanteVerde",
            "MapacheAmarillo",
            "MapacheCeleste",
            "MapacheMorado",
            "MapacheNaranja",
            "MapacheRojo",
            "MapacheRosa",
            "MapacheVerde",
            "PandaAmarillo",
            "PandaCeleste",
            "PandaMorado",
            "PandaNaranja",
            "PandaRojo",
            "PandaRosa",
            "PandaVerde"
      ];

  final List<String> imagen=[



        "assets/images/perfil/tucan-amarillo.png",
        "assets/images/perfil/tucan-celeste.png",
        "assets/images/perfil/tucan-morado.png",
        "assets/images/perfil/tucan-naranja.png",
        "assets/images/perfil/tucan-rojo.png",
        "assets/images/perfil/tucan-rosa.png",
        "assets/images/perfil/tucan-verde.png",
  ];
}